---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpressd
spec:
  rules:
    - http:
        paths:
          - path: /wordpress
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
