apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  project: default
  source:
    path: apps/
    repoURL: https://github.com/igorGevaerd/argo-cd-test.git
    targetRevision: wordpress-with-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true