apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloWorld
  namespace: tools
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/kustomize.git
    targetRevision: HEAD
    path: examples/helloWorld/
  destination:
    server: https://kubernetes.default.svc
    namespace: default