apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true