apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: tools
spec:
  project: default
  source:
    repoURL: https://github.com/igorGevaerd/argo-cd-test.git
    targetRevision: add-apps-base
    path: bases/wordpress-example/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true