apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/kubernetes-sigs/kustomize/examples/wordpress/wordpress
- github.com/kubernetes-sigs/kustomize/examples/wordpress/mysql

patchesStrategicMerge:
- wordpress-custom.yaml