apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  project: default
  source:
    chart: kube-prometheus-stack
    # helm:
    #   values: |
    #     pushgateway:
    #       enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 34.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true